name: Build and deploy .NET application to Container App razor60noauthaca-app-20220331013
on:
  push:
    branches:
    - master
env:
  CONTAINER_APP_CONTAINER_NAME: andy41container
  CONTAINER_APP_NAME: razor60noauthaca-app-20220331013
  CONTAINER_APP_RESOURCE_GROUP_NAME: andy0401LinuxGroup
  CONTAINER_REGISTRY_LOGIN_SERVER: razor60noauthaca20220331014335.azurecr.io
  DOCKER_FILE_PATH: Razor60NoAuthACA/Dockerfile
  PROJECT_NAME_FOR_DOCKER: razor60noauthaca
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.Razor60NoAuthACA20220331014335_USERNAME_FFFF }}
        password: ${{ secrets.Razor60NoAuthACA20220331014335_PASSWORD_FFFF }}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.razor60noauthaca_app_20220331013_SPN }}
    - name: Deploy to containerapp
      uses: azure/CLI@v1
      with:
        inlineScript: >
          echo "Installing containerapp extension"

          az extension add --name containerapp --yes

          echo "Starting Deploying"

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} -i ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }} --debug
    - name: logout
      run: >
        az logout
